application: new-project-template
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /materialize_css
  static_dir: materialize/css

- url: /stylesheets
  static_dir: stylesheets

- url: /images
  static_dir: images

- url: /js
  static_dir: materialize/js

- url: /fonts
  static_dir: materialize/fonts  

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /welcome
  script: welcome.app

- url: /signup
  script: signup.app

- url: /thanks
  script: thanks.app

- url: /todo_list
  script: todo_list.app

- url: /ascii_chan
  script: ascii_chan.app

- url: /blog.*
  script: blog.app

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest


